{% set name = "singledispatch" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ad18e5a55c54a836a695a4e7c12faa05adfe88c7eeb64dcd331a4b13934c3b6

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools >=77
    - setuptools-scm >=3.4.1
    - pip
  run:
    - python

test:
  source_files:
    - test_singledispatch.py
  requires:
    - pip
    - pytest
  imports:
    - singledispatch
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest test_singledispatch.py -v

about:
  home: https://github.com/jaraco/singledispatch
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Transforms a function into a single-dispatch generic function
  description: |
    This library brings functools.singledispatch from Python 3.4 to Python
    2.6-3.3.
  doc_url: https://docs.python.org/3/library/functools.html#functools.singledispatch
  dev_url: https://github.com/jaraco/singledispatch

extra:
  recipe-maintainers:
    - jakirkham
