{% set version = "4.1.2" %}

package:
  name: singledispatch
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/singledispatch/singledispatch-{{ version }}.tar.gz
  sha256: 0ad18e5a55c54a836a695a4e7c12faa05adfe88c7eeb64dcd331a4b13934c3b6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=77
    - setuptools_scm >=3.4.1
    - toml
    - setuptools-scm >=3.4.1
    - coherent.licensed
  run:
    - python
    - six
  run_constrained:
    - pytest-checkdocs >=2.4
    - pytest-enabler >=2.2

test:
  imports:
    - singledispatch
    - singledispatch.helpers
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://docs.python.org/3/library/functools.html#functools.singledispatch
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Transforms a function into a single-dispatch generic function
  description: |
    This library brings functools.singledispatch from Python 3.4 to Python
    2.6-3.3.
  doc_url: http://docs.python.org/3/library/functools.html#functools.singledispatch
  doc_source_url: https://github.com/jaraco/singledispatch/blob/main/README.rst
  dev_url: https://github.com/jaraco/singledispatch

extra:
  recipe-maintainers:
    - jakirkham
