{% set version = "3.7.0" %}

package:
  name: singledispatch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/singledispatch/singledispatch-{{ version }}.tar.gz
  sha256: c1a4d5c1da310c3fd8fccfb8d4e1cb7df076148fd5d858a819e37fffe44f3092

build:
  noarch: python
  number: 1001
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python
    - six

test:
  imports:
    - singledispatch
    - singledispatch.helpers
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://docs.python.org/3/library/functools.html#functools.singledispatch
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Transforms a function into a single-dispatch generic function
  description: |
    This library brings functools.singledispatch from Python 3.4 to Python
    2.6-3.3.
  doc_url: http://docs.python.org/3/library/functools.html#functools.singledispatch
  doc_source_url: https://github.com/jaraco/singledispatch/blob/main/README.rst
  dev_url: https://github.com/jaraco/singledispatch

extra:
  recipe-maintainers:
    - jakirkham
