travis:
  secure:
    BINSTAR_TOKEN: bS+tueWnLfNx5aEPSzafj8ZlbVLxwcpNVS0ND7IzYV6WBdglCJpzx/C2DFkbF0DJiqyqbeZ9xT+XEzKz8k6OXNzGCuD0sEj2OhmnQkEkPWmIjZeHIjz2voNlpEi1cQq0C6oBARN8HwlEu+/nt/CZmieficDcHklxC4/fy1NduY0c8cFixw5eMXRqMDqvCLwtIywoZ2sYMriPwKGDlC311k5q3UYYhlOBfD0ypsKpuVgMZ9L9M/bpD8mUcq8Wy4+90X1VjpPGbJ7OHZj7ApwQ+w9CjriEOV/J14qayM1SGzhaVcqWk0/lxcywcQUsuOxgJd7MVcaKGWqDsWllEUN11omIzznfD16A6DPVEgPIw2ivkbShfHxlcC5O8Hy4MeEkPmk11gCRZYRBBxAqOGA2AVS5rNKYDRnw0mNkHRo3d7f1zlEsNS01520frNg8SwYKV4ZWGWKi36zOcAfzlb1XkzMDGeyA+xPI1VdaxIMFiS+AKowc1/keCpBHp8S5lFg1dUVNXAmL0KBqpkCASlTnw6FDuUwWpYhkzW7aX532goqsv7xrMGupOPOuJNo6Cs/M3661YCBo8woljuffx9K8pmlW5AFhox65YUhwSQ21PY+ZfZWF92X2pQiLIz3eTPlb4Ox0IxjVsh8a0U+NT9yPiVKsBLXNA1arCGNtx2CjbFk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
